site_name: XYZ Intranet
site_url: https://plpilon.github.io/my-intranet-prototype/

theme:
  name: null
  custom_dir: theme

plugins:
  - search:
      lang: [en, fr]
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          default: true
          nav:
            - Home: index.md
            - Employee Resources: resources.md
        - locale: fr
          name: Français
          nav:
            - Accueil: index.md
            - Ressources pour les employés: resources.md

markdown_extensions:
  - md_in_html
  - attr_list
