site_name: Defence Investment Agency Intranet
site_url: https://plpilon.github.io/my-intranet-prototype/

theme:
  name: null
  custom_dir: theme

plugins:
  - search:
      lang: [en, fr]
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          default: true
        - locale: fr
          name: Français

nav:
  - Home: index.md
  - Employee Resources: resources.md

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          # English Nav Labels
          nav:
            - Home: index.md
            - Employee Resources: resources.md
        - locale: fr
          name: Français
          # French Nav Labels
          nav:
            - Accueil: index.md
            - Ressources pour les employés: resources.md

# ADD THIS SECTION
markdown_extensions:
  - md_in_html
  - attr_list
